<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lugares [
    <!ELEMENT lugares (paises, ciudades)>
    <!ELEMENT paises (pais)*>
    <!ELEMENT pais (#PCDATA)>
    <!ATTLIST pais cod ID #REQUIRED>
    <!ELEMENT ciudades (ciudad)*>
    <!ELEMENT ciudad (#PCDATA)>
    <!ATTLIST ciudad pais IDREF #IMPLIED>
    ]>

<lugares>
  <paises>
    <pais cod="1">Argentina</pais>
    <pais cod="2">Austria</pais>
    <pais cod="3">Jap√≥n</pais>
    <pais cod="4">Noruega</pais>
  </paises>
  <ciudades>
    <ciudad pais="3">Osaka</ciudad>
    <ciudad>Oslo</ciudad>
    <ciudad pais="">Sevilla</ciudad>
    <ciudad pais="3">Tokio</ciudad>
    <ciudad pais="2">Viena</ciudad>
  </ciudades>
</lugares>