<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ropa [
    <!ELEMENT ropa (nombre, color*)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT color (#PCDATA)>
    ]>

<ropa>
  <nombre>gorra</nombre>
  <color>rojo</color>
  <color>blanco</color>
  <nombre>ba√±ador</nombre>
  <color>verde</color>
  <color>azul</color>
</ropa>