<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE herramientas [
    <!ELEMENT herramientas (producto)*>
    <!ELEMENT producto (identificacion, nombre)>
    <!ELEMENT identificacion (#PCDATA | codigo | id)*>
    <!ELEMENT codigo (#PCDATA)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    ]>

<herramientas>
  <nombre>martillo</nombre>
  <identificacion>
    Quedan 14 unidades.
    <codigo>MAR264</codigo>
  </identificacion>
  <identificacion>
    <codigo>DES387</codigo>
    <id>678984</id>
    No hay stock.
    <nombre>destornillador</nombre>
  </identificacion>
</herramientas>