<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE forma [
  <!ELEMENT forma (nombre, caracteristicas, numero_de_lados)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT caracteristicas (color, dimensiones)>
  <!ELEMENT color (#PCDATA)>
  <!ELEMENT dimensiones (#PCDATA)>
  <!ELEMENT numero_de_lados (#PCDATA)>
]>

<forma>
  <nombre>rombo</nombre>
  <caracteristicas>
    <color>naranja</color>
    <dimensiones>2</dimensiones>
  </caracteristicas>
  <numero_de_lados>4</numero_de_lados>
</forma>